config/routes.rb
ShiftManage::Application.routes.draw do

  namespace :manage do
    namespace :shift do
      resources :regulars
      resources :irregular
    end
    resources :shift do
      collection do
        get :shift_list
        get :past_shift_list
      end
    end
  end

  namespace :main do
    namespace :shift do
      resources :regulars do
        resources :entries
        member do
          get :apply
          get :apply_status
        end
      end
    end
    resources :shift
  end
  resources :main

end

app/models/main/shift.rb
module Main::Shift
  def self.table_name_prefix
    'main_shift_regulars_'
  end
end

app/models/main/shift/regulars/input_regular_shift.rb
class Main::Shift::Regulars::InputRegularShift < ActiveRecord::Base
  attr_accessible :irs_condition, :irs_date_id, :irs_deside_lect1, :irs_deside_lect2, :irs_deside_lect3, :irs_deside_lect4, :irs_deside_lect5, :irs_lect1, :irs_lect2, :irs_lect3, :irs_lect4, :irs_lect5, :irs_username_id
end

app/models/manage.rb
module Manage
  def self.table_name_prefix
    'manage_'
  end
end

app/models/shift_days.rb
class ShiftDays < ActiveRecord::Base
  attr_accessible :condition, :manage_shift_id, :shift_day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main/shift/entries_controller.rb
class Main::Shift::EntriesController < MainController
  def index
  end
end

app/controllers/main/shift/regulars_controller.rb
class Main::Shift::RegularsController < MainController
  def apply
  	@apply_rs = Manage::Shift::Regular.find(params[:id])
  	@irs      = Main::Shift::Regulars::InputRegularShift.new
  end

  def apply_status
  	@entry_status     = Manage::Shift::Regular.find(params[:id])
  	@entry_Mon_status = Main::Shift::Regulars::InputRegularShift.where(:irs_date_id => @entry_status.rs_Mon)
  end

  def create
  end
end

app/controllers/main/shift_controller.rb
class Main::ShiftController < MainController
  def index
  	@rs = Manage::Shift::Regular.where("rs_input_limit_date > ?", Date.today)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	layout 'main'
	def index
	end
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  layout 'main'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main/shift/regular_helper.rb
module Main::Shift::RegularHelper

  def table_output(status)
  	case status
  	  when 1
  	  	"講義"
  	  when 2
  	  	"勤務可能"
  	  when 3
  	  	"サークル"
  	  when 4
  	  	"勤務不可能"
  	end
  end 

  def morning_work_time(status1, status2)
  	if status1 == 2 && status2 == 2
  	  "10:00 ~ 12:30"
  	elsif status1 == 2 && status2 != 2
  	  "10:00 ~ 10:30"
  	elsif status1 != 2 && status2 == 2
  	  "10:45 ~ 12:30"
  	else
  	  "-"
  	end 
  end

  def afternoon_work_time(status1, status2, status3)
  	if status1 == 2 && status2 == 2 && status3 == 2
  	  "13:15 ~ 19:00"
  	elsif status1 == 2 && status2 == 2 && status3 != 2
  	  "13:15 ~ 16:30"
  	elsif status1 == 2 && status2 != 2 && status3 != 2
  	  "13:15 ~ 14:45"
  	elsif status1 == 2 && status2 != 2 && status3 == 2
  	  "13:15 ~ 14:45¥n16:45 ~ 19:00"
  	elsif status1 != 2 && status2 == 2 && status3 != 2
  	  "15:00 ~ 16:30"
  	elsif status1 != 2 && status2 != 2 && status3 == 2
  	  "16:45 ~ 19:00"
  	else
  	  "-"
  	end 
  end

  def total_work_time(status1, status2, status3, status4, status5)
  	time = 0
  	if status1 == 2
  	  time += 90
  	end
  	if status2 == 2
  	  time += 90
  	end
  	if status3 == 2
  	  time += 90
  	end
  	if status4 == 2
  	  time += 90
  	end
  	if status5 == 2
  	  time += 90
  	end
  	if status1 ==2 && status2 ==2
  	  time += 15
  	end
  	if status3 ==2 && status4 ==2
  	  time += 15
  	end
  	if status4 ==2 && status5 ==2
  	  time += 15
  	end
  	return time
  end
end

app/helpers/main/shift/regulars/entries_helper.rb
module Main::Shift::Regulars::EntriesHelper
end

app/helpers/main/shift_helper.rb
module Main::ShiftHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/manage_helper.rb
module ManageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShiftManage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShiftManage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'サポセンシフト管理システム', main_index_path, {:class => "brand"} %>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              Logged in as <a href="#" class="navbar-link">Username</a>
            </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">メニュー</li>
              <li><%= link_to 'トップページ', main_index_path %></li>
              <li><%= link_to 'シフト入力', main_shift_index_path %></li>
              <li><a href="#">シフト確認</a></li>
              <li><a href="#"></a></li>
              <li class="nav-header">リーダーメニュー</li>
              <li><%= link_to 'シフト作成', manage_shift_index_path %></li>
              <li><%= link_to 'シフト編集', shift_list_manage_shift_index_path %></li>
              <li><%= link_to '過去のシフト情報', past_shift_list_manage_shift_index_path %></li>
              <li class="nav-header">システムメニュー</li>
              <li><a href="#">ユーザ管理</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <%= yield %>
          </div>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p align="center">&copy; ISMC Support Center</p>
      </footer>

    </div><!--/.fluid-container-->
    </html>

app/views/main/_form.html.erb
<table class="table table-bordered">
<tr>
	<td></td>
	<td>1コマ目</td>
	<td>2コマ目</td>
	<td>3コマ目</td>
	<td>4コマ目</td>
	<td>5コマ目</td>
</tr>
<tr>
	<td>中奥</td>
	<td>講義</td>
	<td>講義</td>
	<td>勤務</td>
	<td>勤務</td>
	<td></td>
</tr>
</table>

app/views/main/index.html.erb
<p>受付中シフト一覧</p>
<table class="table table-bordered">
  <tr>
  	<td>受付中シフト</td>
  	<td>入力期限</td>
  </tr>
  <tr>
  	<td>イレギュラーシフト4月22日から4月26日まで</td>
  	<td>4月19日まで</td>
  </tr>
</table>

<p>確定シフト一覧</p>
<table class="table table-bordered">
  <tr>
  	<td>確定シフト</td>
  </tr>
  <tr>
  	<td>イレギュラーシフト4月8日から4月12日まで</td>
  </tr>
</table>

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">月曜日</a></li>
    <li><a href="#tab2" data-toggle="tab">火曜日</a></li>
    <li><a href="#tab3" data-toggle="tab">水曜日</a></li>
    <li><a href="#tab4" data-toggle="tab">木曜日</a></li>
    <li><a href="#tab5" data-toggle="tab">金曜日</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <p>月曜日コンテンツ</p>
      <%= render 'form' %>
    </div>
    <div class="tab-pane" id="tab2">
      <p>火曜日コンテンツ</p>
      <%= render 'form' %>
    </div>
    <div class="tab-pane" id="tab3">
      <p>水曜日コンテンツ</p>
      <%= render 'form' %>
    </div>
    <div class="tab-pane" id="tab4">
      <p>木曜日コンテンツ</p>
      <%= render 'form' %>
    </div>
    <div class="tab-pane" id="tab5">
      <p>金曜日コンテンツ</p>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/main/shift/index.html.erb
<h3>入力受付中シフト一覧</h3>
<h4>レギュラーシフト</h4>
<% if @rs.empty? then %>
  <p>現在入力受付中のレギュラーシフトはありません。</p>
<% else %>
  <table class="table table-borderd">
    <tr>
      <th>レギュラーシフト名</th>
      <th>入力期限</th>
      <th colspan="2">操作</th>
    </tr>
	  <% @rs.each do |rs| %>
	    <tr>
	      <td><%= rs.rs_name %></td>
	      <td><%= rs.rs_input_limit_date %></td>
	      <td><%= link_to 'シフト申請',  apply_main_shift_regular_path(rs.id), {:class => "btn btn-block btn-info"}  %></td>
	      <td><%= link_to '申請状態確認',  apply_status_main_shift_regular_path(rs.id), {:class => "btn btn-block btn-warning"}  %></td>
	    </tr>
	  <% end %>
  </table>
<% end %>

app/views/main/shift/regulars/apply.html.erb
<h3>レギュラーシフト「<%= @apply_rs.rs_name %>」申請画面</h3>
<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">月曜日</a></li>
    <li><a href="#tab2" data-toggle="tab">火曜日</a></li>
    <li><a href="#tab3" data-toggle="tab">水曜日</a></li>
    <li><a href="#tab4" data-toggle="tab">木曜日</a></li>
    <li><a href="#tab5" data-toggle="tab">金曜日</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <%= form_for @irs, :url => {:controller => :regulars, :action => :create} do |f| %>
        <table class="table table-bordered">
          <thead>
          	<tr>
							<td></td>
							<td>1コマ目</td>
							<td>2コマ目</td>
							<td>3コマ目</td>          		
							<td>4コマ目</td>
							<td>5コマ目</td>
          	</tr>
          </thead>
        </table>
      <% end %>
    </div>
    <div class="tab-pane" id="tab2">
      <p>Howdy, I'm in Section 2.</p>
    </div>
  </div>
</div>

app/views/main/shift/regulars/apply_status.html.erb
<h3>レギュラーシフト「<%= @entry_status.rs_name %>」申請状況</h3>
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">月曜日</a></li>
    <li><a href="#tab2" data-toggle="tab">火曜日</a></li>
    <li><a href="#tab2" data-toggle="tab">水曜日</a></li>
    <li><a href="#tab2" data-toggle="tab">木曜日</a></li>
    <li><a href="#tab2" data-toggle="tab">金曜日</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <p>I'm in Section 1.</p>
      <table class="table table-bordered">
        <thead>
          <tr>
            <td>スタッフ名</td>
            <td>午前勤務</td>
            <td>午後勤務</td>
            <td>勤務時間</td>
            <td>1コマ目</td>
            <td>2コマ目</td>
            <td>3コマ目</td>
            <td>4コマ目</td>
            <td>5コマ目</td>
          </tr>
        </thead>
        <tbody>
          <% @entry_Mon_status.each do |eMs| %>
            <tr>
              <td><%= eMs.irs_username_id %></td>
              <td><%= morning_work_time(eMs.irs_lect1,eMs.irs_lect2) %></td>
              <td><%= afternoon_work_time(eMs.irs_lect3,eMs.irs_lect4,eMs.irs_lect5) %></td>
              <td><%= total_work_time(eMs.irs_lect1,eMs.irs_lect2,eMs.irs_lect3,eMs.irs_lect4,eMs.irs_lect5) %></td>
              <td><%= table_output(eMs.irs_lect1) %></td>
              <td><%= table_output(eMs.irs_lect2) %></td>
              <td><%= table_output(eMs.irs_lect3) %></td>
              <td><%= table_output(eMs.irs_lect4) %></td>
              <td><%= table_output(eMs.irs_lect5) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="tab-pane" id="tab2">
      <p>Howdy, I'm in Section 2.</p>
    </div>
  </div>
</div>

app/views/scaffold/shift_input_limit:datetime.html.erb
<h1>Scaffold#shift_input_limit:datetime</h1>
<p>Find me in app/views/scaffold/shift_input_limit:datetime.html.erb</p>

app/views/scaffold/shift_memo:text.html.erb
<h1>Scaffold#shift_memo:text</h1>
<p>Find me in app/views/scaffold/shift_memo:text.html.erb</p>

app/views/scaffold/shift_name:string.html.erb
<h1>Scaffold#shift_name:string</h1>
<p>Find me in app/views/scaffold/shift_name:string.html.erb</p>

app/views/scaffold/shift_type:integer.html.erb
<h1>Scaffold#shift_type:integer</h1>
<p>Find me in app/views/scaffold/shift_type:integer.html.erb</p>